---
driver:
  name: vagrant
  box: 'g5stack'
  box_url: 'http://files.vagrantup.com/precise64.box'
  forward_agent: true
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: g5stack
    run_list:
      - recipe[g5stack::default]
      - recipe[g5stack::gitconfig]
    attributes:
      postgresql:
        password:
          postgres: 'password'
