name 'g5stack'
description 'G5 standard base development environment'
version '0.2.0'
maintainer 'G5'
license 'MIT'

depends 'apt', '2.3.10'
depends 'build-essential', '1.4.4'
depends 'phantomjs'

depends 'g5-postgresql'
depends 'g5-rbenv'
depends 'g5-nodejs'
depends 'redisio'
depends 'imagemagick'
