source 'https://supermarket.getchef.com'

cookbook 'g5stack', git: 'git@github.com:G5/g5stack.git'
cookbook 'g5-postgresql', git: 'git@github.com:G5/g5-postgresql.git'
cookbook 'g5-rbenv', git: 'git@github.com:G5/g5-rbenv.git'
cookbook 'g5-nodejs', git: 'git@github.com:G5/g5-nodejs.git'
